{
   "org.json.datatype":{
      "java.date.format":"YYYY-MM-DD'T'HH:mm:ss'Z'",
      "java.date.format.tz":"GMT",
      "java.class.type":"eu.activelogic.android.uone.files.UONode",
      "resource_path":"string:rw",
      "kind":"enum:file|directory:ro",
      "path":"string:rw",
      "is_public":"boolean:rw",
      "parent_path":"string:ro",
      "volume_path":"string:ro",
      "key":"string:ro",
      "when_created":"date:ro",
      "when_changed":"date:ro",
      "generation":"integer:ro",
      "generation_created":"integer:ro",
      "content_path":"string:ro",
      "hash":"string:rw",
      "public_url":"string:ro",
      "size":"integer:rw",
      "has_children":"boolean:ro",
      "is_root":"boolean:ro",
      "children":"list:type:UONode",
      "child":"type:UONode:ro",
   },
   "kind":"directory",
   "when_created":"2010-10-04T20:06:47Z",
   "generation":0,
   "has_children":true,
   "content_path":"/content/~/Ubuntu One",
   "generation_created":0,
   "parent_path":null,
   "is_live":true,
   "resource_path":"/~/Ubuntu One",
   "when_changed":"2013-02-24T04:01:14Z",
   "key":"RRRR",
   "path":"/",
   "volume_path":"/volumes/~/Ubuntu One",
   "children":[
      {
         "kind":"directory",
         "when_created":"2012-09-02T07:34:52Z",
         "generation":1,
         "has_children":true,
         "content_path":"/content/~/Ubuntu One/2006",
         "generation_created":1,
         "parent_path":"/~/Ubuntu One",
         "is_live":true,
         "resource_path":"/~/Ubuntu One/2006",
         "when_changed":"2012-09-02T07:35:18Z",
         "key":"FFFF",
         "path":"/2006",
         "volume_path":"/volumes/~/Ubuntu One"
      },
      {
         "kind":"file",
         "public_url":null,
         "hash":"sha1:284632dd34aad1fbdb844c5ff9fb080d8fac158f",
         "when_created":"2012-07-30T17:46:29Z",
         "generation":1,
         "content_path":"/content/~/Ubuntu One/x.jpg",
         "generation_created":1,
         "parent_path":"/~/Ubuntu One",
         "is_live":true,
         "resource_path":"/~/Ubuntu One/x.jpg",
         "when_changed":"2012-07-30T17:46:35Z",
         "key":"DDDD",
         "is_public":false,
         "path":"/x.jpg",
         "volume_path":"/volumes/~/Ubuntu One",
         "size": 1
      }
   ]
}